#!/bin/bash
IP=$(cat /etc/IP)
if [ ! -d /etc/VPSManager/userteste ]; then
mkdir /etc/VPSManager/userteste
fi
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "Create test user" ; tput sgr0
echo ""
[ "$(ls -A /etc/VPSManager/userteste)" ] && echo -e "\033[1;32mActive Test User!\033[1;37m" || echo -e "\033[1;31mNo active tests!\033[0m"
echo ""
for testeson in $(ls /etc/VPSManager/userteste |sort |sed 's/.sh//g')
do
echo "$testeson"
done
echo ""
echo -ne "\033[1;32mUsername\033[1;37m: "; read nome
if [[ -z $nome ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid name." ; echo "" ; tput sgr0
	exit 1
fi
awk -F : ' { print $1 }' /etc/passwd > /tmp/users 
if grep -Fxq "$nome" /tmp/users
then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "This user already exists." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mPassword\033[1;37m: "; read pass
if [[ -z $pass ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid password." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mLimit\033[1;37m: "; read limit
if [[ -z $limit ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit.
" ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mminutes \033[1;33m(\033[1;31mEx: \033[1;37m60\033[1;33m)\033[1;37m: "; read u_temp
if [[ -z $limit ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit." ; echo "" ; tput sgr0
	exit 1
fi
useradd -M -s /bin/false $nome
(echo $pass;echo $pass) |passwd $nome > /dev/null 2>&1
echo "$pass" > /etc/VPSManager/senha/$nome
echo "$nome $limit" >> /root/usuarios.db
echo "#!/bin/bash
pkill -f "$nome"
userdel --force $nome
grep -v ^$nome[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/VPSManager/senha/$nome > /dev/null 2>&1
rm -rf /etc/VPSManager/userteste/$nome.sh
exit" > /etc/VPSManager/userteste/$nome.sh
chmod +x /etc/VPSManager/userteste/$nome.sh
at -f /etc/VPSManager/userteste/$nome.sh now + $u_temp min > /dev/null 2>&1
clear
echo -e "\033[1;35m╔════════════════════════════════════════════╗"
echo -e "║          🚀✨ GUTLIBE SSH MANAGER ✨🚀         ║"
echo -e "╚════════════════════════════════════════════╝\033[0m"
echo ""
echo -e "\033[1;37m🔹── SSH ACCOUNT DETAILS ──🔹\033[0m"
echo ""
echo -e "\033[1;36m🌐 IP Address     : \033[1;33m$IP\033[0m"
echo -e "\033[1;36m🌐 Hostname       : \033[1;33m$Host\033[0m"
echo -e "\033[1;36m👤 Username       : \033[1;33m$nome\033[0m"
echo -e "\033[1;36m🔑 Password       : \033[1;33m$pass\033[0m"
echo -e "\033[1;36m🚫 Login Limit    : \033[1;33m$limit\033[0m"
echo -e "\033[1;36m⏳ Expiry Time    : \033[1;33m$u_temp minutes\033[0m"
echo ""
echo -e "\033[1;37m🔹── MTN GHANA PAYLOAD 1️⃣ ──🔹\033[0m"
echo ""
echo -e "\033[1;36m📜 GET / HTTP/1.1[crlf]Host: $Host[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]\033[0m"
echo ""
echo -e "\033[1;37m🔹── MTN GHANA PAYLOAD 2️⃣ ──🔹\033[0m"
echo ""
echo -e "\033[1;36m📜 GET ws://[rotate=auth.mtn.com.gh;uhas.edu.gh] HTTP/1.1[crlf]Host: auth.ayo4u.com[crlf]Upgrade: websocket[crlf][crlf] -_- ws:// $Host HTTP/1.1[crlf]Host: auth.ayo4u.com[crlf]Upgrade: websocket[crlf][crlf]\033[0m"
echo ""
echo -e "\033[1;37m🔹── MTN GHANA PAYLOAD 3️⃣ ──🔹\033[0m"
echo ""
echo -e "\033[1;36m📜 GET / HTTP/1.1[crlf]Host: [rotate=www.upsa.edu.gh;mtngh-uat-cd-otycvewgw0hqf68y.edge.mtn-dev.auth0.com][crlf][crlf]- / HTTP/1.1[crlf]Host: $Host[crlf]Upgrade: HTTP/2.0, SHTTP/1.3, IRC/6.9, RTA/x11[crlf]Connection:keep-alive[crlf][crlf]\033[0m"
echo ""
echo -e "\033[1;37m🔹── TELECEL GHANA PAYLOAD ──🔹\033[0m"
echo ""
echo -e "\033[1;36m📜 GET http://91.241.94.160/ HTTP/1.1[crlf]Host: zerod.mobi[crlf]Connection: Upgrade[crlf]Upgrade: Websocket[crlf][crlf]\033[0m"
echo ""
echo -e "\033[1;37m══════════════════════════════════════════════════"
echo -e "     GUTLIBE VPS MANAGER SCRIPT "
echo -e "══════════════════════════════════════════════════\033[0m"

    echo ""
    echo -e "\033[1;33mAfter the defined time of the user \033[1;32m$nome"
    echo -e "\033[1;33mwill be disconnected and deleted.\033[0m"
exit
